### PR TITLE
Feature/test 1

### PR DESCRIPTION
**Pull request by mian3010**

### CODE REVIEW

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by mian3010** [comment]
Retest this please

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Release Notes**
The following issues still needs testing:

|Key|Title|Status|Asignee|
|---|-------|------|----|
|[MSFSUP-179](https://reload.atlassian.net/MSFSUP-179)|For store overskrifter på mobil|Ready for Testing|Morten Bartvig|
|[MSFSUP-29](https://reload.atlassian.net/MSFSUP-29)|Front button view og list of sponsors|Closed|André Kallehauge|

Please test issues, and report status here.
To mark an issue as tested please write '[issue-key] OK'. E.g. XXX-1234 OK.

**Comment by mian3010** [comment]
MSFSUP-179 OK

**Comment by reload-branching-check** [comment]
**Reload Release Notes**
The following issues still needs testing:

|Key|Title|Status|Asignee|
|---|-------|------|----|
|[MSFSUP-29](https://reload.atlassian.net/MSFSUP-29)|Front button view og list of sponsors|Closed|André Kallehauge|

Please test issues, and report status here.
To mark an issue as tested please write '[issue-key] OK'. E.g. XXX-1234 OK.

**Comment by mian3010** [comment]
MSFSUP-29 OK

**Comment by reload-branching-check** [comment]
**Reload Release Notes**

**Comment by mian3010** [comment]
Regenerate release-notes

**Comment by reload-branching-check** [comment]
**Reload Release Notes**

**Comment by mian3010** [comment]
Regenerate release-notes

**Comment by reload-branching-check** [comment]
**Reload Release Notes**
- For store overskrifter på mobil
 https://reload.atlassian.net/MSFSUP-179
- Front button view og list of sponsors
 https://reload.atlassian.net/MSFSUP-29

Ready for merge

**Comment by mian3010** [comment]
Regenerate release-notes

**Comment by reload-branching-check** [comment]
**Reload Release Notes**
- For store overskrifter på mobil
 https://reload.atlassian.net/MSFSUP-179
- Front button view og list of sponsors
 https://reload.atlassian.net/MSFSUP-29

Ready for merge

**Comment by mian3010** [comment]
Regenerate release-notes

**Comment by mian3010** [comment]
Regenerate release-notes

**Comment by reload-branching-check** [comment]
**Reload Release Notes**
- For store overskrifter på mobil
 https://reload.atlassian.net/MSFSUP-179

- Front button view og list of sponsors
 https://reload.atlassian.net/MSFSUP-29


Ready for merge

**Comment by mian3010** [comment]
Retest this please

**Comment by reload-branching-check** [comment]
**Reload Release Notes**
- For store overskrifter på mobil
 https://reload.atlassian.net/MSFSUP-179

- Front button view og list of sponsors
 https://reload.atlassian.net/MSFSUP-29


Ready for merge

**Comment by mian3010** [comment]
Retest this please

**Comment by ghost** [comment]
**Reload Release Notes**
- For store overskrifter på mobil
  https://reload.atlassian.net/MSFSUP-179
- Front button view og list of sponsors
  https://reload.atlassian.net/MSFSUP-29

Ready for merge

**Comment by ghost** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

| SHA | Message | Author | Date |
| --- | --- | --- | --- |
| eac7d2c5ce6677216098adc9497035ffb30af4f5 | Commit on feature-branch | Michael Søby Andersen (michael@megha.it) | 2016-06-06T10:45:49Z |
| 01d6064c201c1a7b3c2b04e43aa3f6875c578a88 | Added something more. MSFSUP-1000 | Michael Søby Andersen (michael@megha.it) | 2016-06-06T11:27:34Z |

**Pull request closed without merging**
