### PR TITLE
Release/1.0.0

### PR DESCRIPTION
**Pull request by mian3010**

### CODE REVIEW

**Comment by reload-branching-check** [comment]
**Reload Release Notes**
The following issues still needs testing:

|Key|Title|Status|Asignee|
|---|-------|------|----|
|[MSFSUP-29](https://reload.atlassian.net/MSFSUP-29)|Front button view og list of sponsors|Closed|André Kallehauge|
|[MSFSUP-179](https://reload.atlassian.net/MSFSUP-179)|For store overskrifter på mobil|Ready for Testing|Morten Bartvig|

Please test issues, and report status here.
To mark an issue as tested please write '[issue-key] OK'. E.g. XXX-1234 OK.

**Comment by mian3010** [comment]
MSFSUP-29 OK
MSFSUP-179 OK

**Comment by reload-branching-check** [comment]
**Reload Release Notes**
- Front button view og list of sponsors
 https://reload.atlassian.net/MSFSUP-29

- For store overskrifter på mobil
 https://reload.atlassian.net/MSFSUP-179


Ready for merge

**Comment by ghost** [comment]
**Reload Release Notes**
- Front button view og list of sponsors
  https://reload.atlassian.net/MSFSUP-29
- For store overskrifter på mobil
  https://reload.atlassian.net/MSFSUP-179

Ready for merge

**Pull request closed without merging**
