### PR TITLE
Commit on feature-branch

### PR DESCRIPTION
**Pull request by mian3010**

### CODE REVIEW

**Comment by mian3010** [comment]
Errors found:
 -No issues referenced in commit eac7d2c5ce6677216098adc9497035ffb30af4f5: 'Commit on feature-branch' by Michael Søby Andersen (michael@megha.it)
 -No issues referenced in commit 01812f18a1af484f42f18496152af6f1078a98bf: 'Added something more.' by Michael Søby Andersen (michael@megha.it)
 -No issues referenced in commit 18266f82fb4b7453f47609ebb2e7313cf76800d7: 'Lets reference two issues. DDC-1234 DDC-1122' by Michael Søby Andersen (michael@megha.it)

**Comment by mian3010** [comment]
Errors found:
 * No issues referenced in commit eac7d2c5ce6677216098adc9497035ffb30af4f5: _Commit on feature-branch_ by Michael Søby Andersen (michael@megha.it)
 * No issues referenced in commit 01812f18a1af484f42f18496152af6f1078a98bf: _Added something more._ by Michael Søby Andersen (michael@megha.it)
 * No issues referenced in commit 18266f82fb4b7453f47609ebb2e7313cf76800d7: _Lets reference two issues. DDC-1234 DDC-1122_ by Michael Søby Andersen (michael@megha.it)

**Comment by mian3010** [comment]
*Reload Branching*
Errors found:
 * No issues referenced in commit eac7d2c5ce6677216098adc9497035ffb30af4f5: _Commit on feature-branch_ by Michael Søby Andersen (michael@megha.it)
 * No issues referenced in commit 01812f18a1af484f42f18496152af6f1078a98bf: _Added something more._ by Michael Søby Andersen (michael@megha.it)
 * No issues referenced in commit 18266f82fb4b7453f47609ebb2e7313cf76800d7: _Lets reference two issues. DDC-1234 DDC-1122_ by Michael Søby Andersen (michael@megha.it)

**Comment by mian3010** [comment]
**Reload Branching**
Errors found:
 * No issues referenced in commit eac7d2c5ce6677216098adc9497035ffb30af4f5: _Commit on feature-branch_ by Michael Søby Andersen (michael@megha.it)
 * No issues referenced in commit 01812f18a1af484f42f18496152af6f1078a98bf: _Added something more._ by Michael Søby Andersen (michael@megha.it)
 * No issues referenced in commit 18266f82fb4b7453f47609ebb2e7313cf76800d7: _Lets reference two issues. DDC-1234 DDC-1122_ by Michael Søby Andersen (michael@megha.it)

**Comment by mian3010** [comment]
**Reload Branching**
Errors found:
 * No issues referenced in commit eac7d2c5ce6677216098adc9497035ffb30af4f5: 
Commit on feature-branch
By Michael Søby Andersen (michael@megha.it)
 * No issues referenced in commit 01812f18a1af484f42f18496152af6f1078a98bf: 
Added something more.
By Michael Søby Andersen (michael@megha.it)
 * No issues referenced in commit 18266f82fb4b7453f47609ebb2e7313cf76800d7: 
Lets reference two issues. DDC-1234 DDC-1122
By Michael Søby Andersen (michael@megha.it)

**Comment by mian3010** [comment]
**Reload Branching**
|SHA|Message|Author|Date||---|-------|------|----||eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen ()|||01812f18a1af484f42f18496152af6f1078a98bf|Added something more.|Michael Søby Andersen ()|||18266f82fb4b7453f47609ebb2e7313cf76800d7|Lets reference two issues. DDC-1234 DDC-1122|Michael Søby Andersen ()||

**Comment by mian3010** [comment]
**Reload Branching**
|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen ()||
|01812f18a1af484f42f18496152af6f1078a98bf|Added something more.|Michael Søby Andersen ()||
|18266f82fb4b7453f47609ebb2e7313cf76800d7|Lets reference two issues. DDC-1234 DDC-1122|Michael Søby Andersen ()||

**Comment by mian3010** [comment]
**Reload Branching**

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01812f18a1af484f42f18496152af6f1078a98bf|Added something more.|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|
|18266f82fb4b7453f47609ebb2e7313cf76800d7|Lets reference two issues. DDC-1234 DDC-1122|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:35:35Z|

**Comment by mian3010** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01812f18a1af484f42f18496152af6f1078a98bf|Added something more.|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|
|18266f82fb4b7453f47609ebb2e7313cf76800d7|Lets reference two issues. DDC-1234 DDC-1122|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:35:35Z|

**Comment by mian3010** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|
|371cc127ed7ba7819425e33b6bf3e24d6a9d1053|Lets reference two issues. MSFSUP-179 MSFSUP-29|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:35:35Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|
|371cc127ed7ba7819425e33b6bf3e24d6a9d1053|Lets reference two issues. MSFSUP-179 MSFSUP-29|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:35:35Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|
|371cc127ed7ba7819425e33b6bf3e24d6a9d1053|Lets reference two issues. MSFSUP-179 MSFSUP-29|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:35:35Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|
|371cc127ed7ba7819425e33b6bf3e24d6a9d1053|Lets reference two issues. MSFSUP-179 MSFSUP-29|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:35:35Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|
|371cc127ed7ba7819425e33b6bf3e24d6a9d1053|Lets reference two issues. MSFSUP-179 MSFSUP-29|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:35:35Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|
|371cc127ed7ba7819425e33b6bf3e24d6a9d1053|Lets reference two issues. MSFSUP-179 MSFSUP-29|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:35:35Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|
|371cc127ed7ba7819425e33b6bf3e24d6a9d1053|Lets reference two issues. MSFSUP-179 MSFSUP-29|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:35:35Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|
|371cc127ed7ba7819425e33b6bf3e24d6a9d1053|Lets reference two issues. MSFSUP-179 MSFSUP-29|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:35:35Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|
|371cc127ed7ba7819425e33b6bf3e24d6a9d1053|Lets reference two issues. MSFSUP-179 MSFSUP-29|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:35:35Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by mian3010** [comment]
Test

**Comment by mian3010** [comment]
Test 2

**Comment by mian3010** [comment]
Retest this please

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by mian3010** [comment]
Retest this please

**Comment by reload-branching-check** [comment]
**Reload Branching**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by mian3010** [comment]
Retest this please

**Comment by mian3010** [comment]
Retest this please

**Comment by reload-branching-check** [comment]
_Reload Commit Checker_
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by mian3010** [comment]
Retest this please

**Comment by reload-branching-check** [comment]
_Reload Commit Checker_
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by mian3010** [comment]
Retest this please

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by mian3010** [comment]
Retest this please

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by mian3010** [comment]
Retest this please

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Comment by mian3010** [comment]
Retest this please

**Comment by mian3010** [comment]
Retest this please

**Comment by reload-branching-check** [comment]
**Reload Commit Checker**
The following commits does not correctly reference a Jira issue:

|SHA|Message|Author|Date|
|---|-------|------|----|
|eac7d2c5ce6677216098adc9497035ffb30af4f5|Commit on feature-branch|Michael Søby Andersen (michael@megha.it)|2016-06-06T10:45:49Z|
|01d6064c201c1a7b3c2b04e43aa3f6875c578a88|Added something more. MSFSUP-1000|Michael Søby Andersen (michael@megha.it)|2016-06-06T11:27:34Z|

**Pull request closed without merging**
